# -*- conf -*-

term=xterm-256color
title=Foot
font=monospace:size=12
initial-window-size-chars=100x30
bold-text-in-bright=yes
selection-target=clipboard

[scrollback]
lines=10000
multiplier=3.0

[cursor]
style=underline
underline-thickness=1.5

[mouse]
hide-when-typing=yes

[key-bindings]
clipboard-copy=Control+c Control+Shift+c XF86Copy
clipboard-paste=Control+v Control+Shift+v XF86Paste
search-start=Control+Shift+f Control+Shift+b Control+Shift+r
font-reset=Control+0 Control+KP_0

[search-bindings]
clipboard-paste=Control+v Control+Shift+v Control+y XF86Paste
primary-paste=Shift+Insert

[colors-dark]
alpha=0.8
background=2E3440
foreground=D8DEE9
regular0=3B4252
regular1=BF616A
regular2=A3BE8C
regular3=EBCB8B
regular4=81A1C1
regular5=B48EAD
regular6=88C0D0
regular7=E5E9F0
bright0=4C566A
bright1=BF616A
bright2=A3BE8C
bright3=EBCB8B
bright4=81A1C1
bright5=B48EAD
bright6=8FBCBB
bright7=ECEFF4
