# Desktop — widgets, wallpaper

# ── Desktop widgets ────────────────────────────────
[desktop_widgets]
enabled = false

# ── Wallpaper ──────────────────────────────────────
[wallpaper]
enabled               = true
fill_mode             = "crop"         # center | crop | fit | stretch | repeat | span
fill_color            = "#111111"
transition            = ["fade", "wipe", "disc", "stripes", "zoom", "honeycomb"]
transition_duration   = 1500
edge_smoothness       = 0.3
transition_on_startup = false
directory             = "/home/nelly/Wallpapers"